jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '8'
    - continue-on-error: true
      name: Check java checkstyle
      run: mvn checkstyle:check
    - continue-on-error: true
      name: Test
      run: mvn install
name: QA check
on:
  repository_dispatch:
    types: trigger-ga___check.yml
